export const tourPdfTranslations = {
  es: {
    "This tour travels along the Pacific coast toward Quepos and Manuel Antonio, passing ocean views, coastal towns and palm plantations before reaching the park.": "Este tour recorre la costa del Pacifico hacia Quepos y Manuel Antonio, pasando por vistas al oceano, pueblos costeros y plantaciones de palma antes de llegar al parque.",
    "Inside the park, a bilingual guide leads the trail walk with chances to see monkeys, iguanas, tropical birds and sloths, followed by time to relax on the beach.": "Dentro del parque, un guia bilingue dirige la caminata por los senderos, con oportunidades de ver monos, iguanas, aves tropicales y perezosos, seguida de tiempo para relajarse en la playa.",
    "Manuel Antonio": "Manuel Antonio", "Quepos": "Quepos",
    "Nature Combo brings together three classic Costa Rica stops: a coffee experience with breakfast, the crater area of Poas Volcano and the La Paz Waterfall Gardens.": "Nature Combo reune tres paradas clasicas de Costa Rica: una experiencia de cafe con desayuno, la zona del crater del Volcan Poas y los Jardines de la Catarata La Paz.",
    "The La Paz visit includes rainforest paths, the Magia Blanca waterfall area, wildlife sanctuary exhibits and a buffet-style lunch.": "La visita a La Paz incluye senderos de bosque lluvioso, el area de la catarata Magia Blanca, exhibiciones del santuario de vida silvestre y un almuerzo tipo bufet.",
    "Beach Day is designed for travelers who want an easy Pacific escape with resort access, calm beach time and a relaxed lunch included.": "Beach Day esta disenado para viajeros que desean una escapada sencilla al Pacifico con acceso al resort, tiempo tranquilo en la playa y un almuerzo relajado incluido.",
    "The resort setting can include natural trails and a butterfly garden, giving the day a simple mix of beach, rest and light nature exploration.": "El entorno del resort puede incluir senderos naturales y un mariposario, combinando playa, descanso y una exploracion ligera de la naturaleza.",
    "Resort access": "Acceso al resort", "Light clothes": "Ropa ligera",
    "This San Jose city tour uses a double-decker sightseeing bus to connect the capital's main cultural and historic highlights.": "Este tour por San Jose utiliza un autobus turistico de dos pisos para conectar los principales atractivos culturales e historicos de la capital.",
    "The route can include the Central Market, National Theater lobby, Gold Museum, Art Museum, Central Avenue and a typical lunch or dinner according to the selected schedule.": "La ruta puede incluir el Mercado Central, el vestibulo del Teatro Nacional, el Museo del Oro, el Museo de Arte, la Avenida Central y un almuerzo o cena tipica segun el horario seleccionado.",
    "Central Market": "Mercado Central",
    "The rafting program offers options for travelers who want either a family-friendly river experience or a stronger adrenaline route.": "El programa de rafting ofrece opciones para viajeros que buscan una experiencia familiar en el rio o una ruta con mayor adrenalina.",
    "The Savegre route is known for class II and III rapids with rainforest scenery, while the Naranjo option can bring class III and IV rapids through canyon and rural landscapes.": "La ruta del Savegre es conocida por sus rapidos de clase II y III con paisajes de bosque lluvioso, mientras que la opcion del Naranjo puede ofrecer rapidos de clase III y IV entre canones y paisajes rurales.",
    "Gulf of Nicoya": "Golfo de Nicoya", "La Fortuna": "La Fortuna", "Sarchi": "Sarchi", "Dinner": "Cena", "Cartago": "Cartago", "Basilica": "Basilica", "Tarcoles": "Tarcoles"
  },
  fr: {
    "This tour travels along the Pacific coast toward Quepos and Manuel Antonio, passing ocean views, coastal towns and palm plantations before reaching the park.": "Cette excursion longe la cote Pacifique vers Quepos et Manuel Antonio, avec des vues sur l'ocean, des villages cotiers et des plantations de palmiers avant d'arriver au parc.",
    "Inside the park, a bilingual guide leads the trail walk with chances to see monkeys, iguanas, tropical birds and sloths, followed by time to relax on the beach.": "Dans le parc, un guide bilingue dirige la promenade sur les sentiers, avec des possibilites d'observer singes, iguanes, oiseaux tropicaux et paresseux, puis du temps pour se detendre sur la plage.",
    "Manuel Antonio": "Manuel Antonio", "Quepos": "Quepos",
    "Nature Combo brings together three classic Costa Rica stops: a coffee experience with breakfast, the crater area of Poas Volcano and the La Paz Waterfall Gardens.": "Nature Combo reunit trois etapes classiques du Costa Rica : une experience autour du cafe avec petit-dejeuner, la zone du cratere du volcan Poas et les jardins de la cascade La Paz.",
    "The La Paz visit includes rainforest paths, the Magia Blanca waterfall area, wildlife sanctuary exhibits and a buffet-style lunch.": "La visite de La Paz comprend des sentiers en foret tropicale, la cascade Magia Blanca, les espaces du sanctuaire animalier et un dejeuner buffet.",
    "Beach Day is designed for travelers who want an easy Pacific escape with resort access, calm beach time and a relaxed lunch included.": "Beach Day est concu pour les voyageurs souhaitant une escapade facile sur le Pacifique, avec acces au complexe, temps libre a la plage et dejeuner detendu inclus.",
    "The resort setting can include natural trails and a butterfly garden, giving the day a simple mix of beach, rest and light nature exploration.": "Le complexe peut inclure des sentiers naturels et un jardin de papillons, pour une journee combinant plage, repos et decouverte legere de la nature.",
    "Resort access": "Acces au complexe", "Light clothes": "Vetements legers",
    "This San Jose city tour uses a double-decker sightseeing bus to connect the capital's main cultural and historic highlights.": "Cette visite de San Jose utilise un autobus touristique a deux etages pour relier les principaux sites culturels et historiques de la capitale.",
    "The route can include the Central Market, National Theater lobby, Gold Museum, Art Museum, Central Avenue and a typical lunch or dinner according to the selected schedule.": "L'itineraire peut inclure le Marche central, le hall du Theatre national, le Musee de l'or, le Musee d'art, l'Avenue centrale et un dejeuner ou diner typique selon l'horaire choisi.",
    "Central Market": "Marche central",
    "The rafting program offers options for travelers who want either a family-friendly river experience or a stronger adrenaline route.": "Le programme de rafting propose des options pour une experience familiale sur la riviere ou un parcours plus riche en adrenaline.",
    "The Savegre route is known for class II and III rapids with rainforest scenery, while the Naranjo option can bring class III and IV rapids through canyon and rural landscapes.": "Le parcours Savegre est connu pour ses rapides de classes II et III dans un decor de foret tropicale, tandis que l'option Naranjo peut proposer des rapides de classes III et IV entre canyons et paysages ruraux.",
    "Gulf of Nicoya": "Golfe de Nicoya", "La Fortuna": "La Fortuna", "Sarchi": "Sarchi", "Dinner": "Diner", "Cartago": "Cartago", "Basilica": "Basilique", "Tarcoles": "Tarcoles"
  }
};
