export const rentACarRates = {
  diario: [
    { categoria: "MINI", ejemplo: "TOYOTA AGYA", transmision: "MANUAL", sin_seguro: 36, seguro_basico: 56, full_cover: 89.1 },
    { categoria: "ECONOMICO", ejemplo: "SUZUKI SWIFT", transmision: "AUTOMATICO", sin_seguro: 45, seguro_basico: 64, full_cover: 97.35 },
    { categoria: "COMPACTO", ejemplo: "VOLKSWAGEN NIVUS", transmision: "AUTOMATICO", sin_seguro: 54, seguro_basico: 74, full_cover: 107.25 },
    { categoria: "MID SIZE AUT.", ejemplo: "TOYOTA COROLLA", transmision: "AUTOMATICO", sin_seguro: 59, seguro_basico: 79, full_cover: 112.2 },
    { categoria: "ECONOMY SUV 4X2", ejemplo: "TOYOTA YARIS CROSS", transmision: null, sin_seguro: 50, seguro_basico: 74, full_cover: 107.25 },
    { categoria: "COMPACTO SUV 4X2", ejemplo: "TOYOTA COROLLA CROSS", transmision: "AUTOMATICO", sin_seguro: 53, seguro_basico: 78, full_cover: 110.55 },
    { categoria: "MID SIZE 4X4", ejemplo: "SUZUKI VITARA", transmision: "AUTOMATICO", sin_seguro: 78, seguro_basico: 102, full_cover: 135.3 },
    { categoria: "STANDARD 4X4", ejemplo: "TOYOTA RAV4", transmision: "AUTOMATICO", sin_seguro: 89, seguro_basico: 114, full_cover: 146.85 },
    { categoria: "SPECIAL 4X2", ejemplo: "TOYOTA RUSH 4X2", transmision: "AUTOMATICO", sin_seguro: 89, seguro_basico: 114, full_cover: 146.85 },
    { categoria: "STANDARD 4X4 SPORT", ejemplo: "FORD BRONCOS", transmision: null, sin_seguro: 104, seguro_basico: 145, full_cover: 178.2 },
    { categoria: "STANDARD 4X4 ELECTRIC", ejemplo: "TOYOTA BZ4X 4X4", transmision: "AUTOMATICO", sin_seguro: 104, seguro_basico: 145, full_cover: 178.2 },
    { categoria: "PICK-UP 4X4", ejemplo: "TOYOTA HILUX", transmision: "MAN/AUT", sin_seguro: 91, seguro_basico: 132, full_cover: 165 },
    { categoria: "FULL SIZE 4X4", ejemplo: "TOYOTA FORTUNER", transmision: "AUTOMATICO", sin_seguro: 119, seguro_basico: 160, full_cover: 193.05 },
    { categoria: "PREMIUM 4X4", ejemplo: "FORD EVEREST", transmision: "AUTOMATICO", sin_seguro: 139, seguro_basico: 180, full_cover: 212.85 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE", transmision: "MANUAL", sin_seguro: 139, seguro_basico: 180, full_cover: 212.85 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE TECHO BAJO", transmision: null, sin_seguro: 147, seguro_basico: 188, full_cover: 221.1 },
    { categoria: "MICROBUS 4X4", ejemplo: "HYUNDAI STARIA", transmision: "AUTOMATICO", sin_seguro: 155, seguro_basico: 196, full_cover: 229.35 },
    { categoria: "LUXURY", ejemplo: "FORD EXPEDITION", transmision: "AUTOMATICO", sin_seguro: 305, seguro_basico: 347, full_cover: 379.5 }
  ],
  semanal: [
    { categoria: "MINI", ejemplo: "TOYOTA AGYA", transmision: "MANUAL", sin_seguro: 218, seguro_basico: 356.4, full_cover: 587.4 },
    { categoria: "ECONOMICO", ejemplo: "SUZUKI SWIFT", transmision: "AUTOMATICO", sin_seguro: 267, seguro_basico: 405.9, full_cover: 636.9 },
    { categoria: "COMPACTO", ejemplo: "VOLKSWAGEN NIVUS", transmision: "AUTOMATICO", sin_seguro: 327, seguro_basico: 465.3, full_cover: 696.3 },
    { categoria: "MID SIZE AUT.", ejemplo: "TOYOTA COROLLA", transmision: "AUTOMATICO", sin_seguro: 356, seguro_basico: 495, full_cover: 726 },
    { categoria: "ECONOMY SUV 4X2", ejemplo: "TOYOTA YARIS CROSS", transmision: null, sin_seguro: 297, seguro_basico: 470.25, full_cover: 701.25 },
    { categoria: "COMPACTO SUV 4X2", ejemplo: "TOYOTA COROLLA CROSS", transmision: "AUTOMATICO", sin_seguro: 317, seguro_basico: 490.05, full_cover: 721.05 },
    { categoria: "MID SIZE 4X4", ejemplo: "SUZUKI VITARA", transmision: "AUTOMATICO", sin_seguro: 465, seguro_basico: 638.55, full_cover: 869.55 },
    { categoria: "STANDARD 4X4", ejemplo: "TOYOTA RAV4", transmision: "AUTOMATICO", sin_seguro: 535, seguro_basico: 707.85, full_cover: 938.85 },
    { categoria: "SPECIAL 4X2", ejemplo: "TOYOTA RUSH 4X2", transmision: "AUTOMATICO", sin_seguro: 535, seguro_basico: 707.85, full_cover: 938.85 },
    { categoria: "STANDARD 4X4 SPORT", ejemplo: "FORD BRONCOS", transmision: null, sin_seguro: 624, seguro_basico: 912.45, full_cover: 1143.45 },
    { categoria: "STANDARD 4X4 ELECTRIC", ejemplo: "TOYOTA BZ4X 4X4", transmision: "AUTOMATICO", sin_seguro: 624, seguro_basico: 912.45, full_cover: 1143.45 },
    { categoria: "PICK-UP 4X4", ejemplo: "TOYOTA HILUX", transmision: "MAN/AUT", sin_seguro: 545, seguro_basico: 833.25, full_cover: 1064.25 },
    { categoria: "FULL SIZE 4X4", ejemplo: "TOYOTA FORTUNER", transmision: "AUTOMATICO", sin_seguro: 713, seguro_basico: 1001.55, full_cover: 1232.55 },
    { categoria: "PREMIUM 4X4", ejemplo: "FORD EVEREST", transmision: "AUTOMATICO", sin_seguro: 832, seguro_basico: 1120.35, full_cover: 1351.35 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE", transmision: "MANUAL", sin_seguro: 832, seguro_basico: 1120.35, full_cover: 1351.35 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE", transmision: null, sin_seguro: 881, seguro_basico: 1169.85, full_cover: 1400.85 },
    { categoria: "MICROBUS 4X4", ejemplo: "HYUNDAI STARIA", transmision: "AUTOMATICO", sin_seguro: 931, seguro_basico: 1219.35, full_cover: 1450.35 },
    { categoria: "LUXURY", ejemplo: "FORD EXPEDITION", transmision: "AUTOMATICO", sin_seguro: 1832, seguro_basico: 2120.25, full_cover: 2351.25 }
  ],
  mensual: [
    { categoria: "MINI", ejemplo: "TOYOTA AGYA", transmision: "MANUAL", sin_seguro: 871, seguro_basico: 1465.2, full_cover: 2455.2 },
    { categoria: "ECONOMICO", ejemplo: "SUZUKI SWIFT", transmision: "AUTOMATICO", sin_seguro: 1069, seguro_basico: 1663.2, full_cover: 2653.2 },
    { categoria: "COMPACTO", ejemplo: "VOLKSWAGEN NIVUS", transmision: "AUTOMATICO", sin_seguro: 1307, seguro_basico: 1900.8, full_cover: 2890.8 },
    { categoria: "MID SIZE AUT.", ejemplo: "TOYOTA COROLLA", transmision: "AUTOMATICO", sin_seguro: 1426, seguro_basico: 2019.6, full_cover: 3009.6 },
    { categoria: "ECONOMY SUV 4X2", ejemplo: "TOYOTA YARIS CROSS", transmision: null, sin_seguro: 1188, seguro_basico: 1930.5, full_cover: 3036 },
    { categoria: "COMPACTO SUV 4X2", ejemplo: "TOYOTA COROLLA CROSS", transmision: "AUTOMATICO", sin_seguro: 1267, seguro_basico: 2009.7, full_cover: 2999.7 },
    { categoria: "MID SIZE 4X4", ejemplo: "SUZUKI VITARA", transmision: "AUTOMATICO", sin_seguro: 1861, seguro_basico: 2603.7, full_cover: 3709.2 },
    { categoria: "STANDARD 4X4", ejemplo: "TOYOTA RAV4", transmision: "AUTOMATICO", sin_seguro: 2138, seguro_basico: 2880.9, full_cover: 3870.9 },
    { categoria: "SPECIAL 4X2", ejemplo: "TOYOTA RUSH 4X2", transmision: "AUTOMATICO", sin_seguro: 2138, seguro_basico: 2880.9, full_cover: 3870.9 },
    { categoria: "STANDARD 4X4 SPORT", ejemplo: "FORD BRONCOS", transmision: null, sin_seguro: 2495, seguro_basico: 3732.3, full_cover: 4870.8 },
    { categoria: "STANDARD 4X4 ELECTRIC", ejemplo: "TOYOTA BZ4X 4X4", transmision: "AUTOMATICO", sin_seguro: 2495, seguro_basico: 3732.3, full_cover: 4722.3 },
    { categoria: "PICK-UP 4X4", ejemplo: "TOYOTA HILUX", transmision: "MAN/AUT", sin_seguro: 2178, seguro_basico: 3415.5, full_cover: 4405.5 },
    { categoria: "FULL SIZE 4X4", ejemplo: "TOYOTA FORTUNER", transmision: "AUTOMATICO", sin_seguro: 2851, seguro_basico: 4088.7, full_cover: 5227.2 },
    { categoria: "PREMIUM 4X4", ejemplo: "FORD EVEREST", transmision: "AUTOMATICO", sin_seguro: 3326, seguro_basico: 4563.9, full_cover: 5553.9 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE", transmision: "MANUAL", sin_seguro: 3326, seguro_basico: 4563.9, full_cover: 5702.4 },
    { categoria: "MICROBUS 4X2", ejemplo: "TOYOTA HIACE", transmision: null, sin_seguro: 3524, seguro_basico: 4761.9, full_cover: 5751.9 },
    { categoria: "MICROBUS 4X4", ejemplo: "HYUNDAI STARIA", transmision: "AUTOMATICO", sin_seguro: 3722, seguro_basico: 4959.9, full_cover: 5949.9 },
    { categoria: "LUXURY", ejemplo: "FORD EXPEDITION", transmision: "AUTOMATICO", sin_seguro: 7326, seguro_basico: 8563.5, full_cover: 9553.5 }
  ]
};
