export const tourGalleryManifest = {
  "jaco/Aerial_Tram": [
    "img/tours/jaco/Aerial_Tram/Teleferico-2.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-3.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-4.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-5.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-6.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico.webp"
  ],
  "jaco/Canyoning_Tour": [
    "img/tours/jaco/Canyoning_Tour/Canyoning-2.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-3.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-4.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-5.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-6.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-7.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning.webp"
  ],
  "jaco/Carara_National_Park": [
    "img/tours/jaco/Carara_National_Park/carara-1.webp",
    "img/tours/jaco/Carara_National_Park/carara-2.webp",
    "img/tours/jaco/Carara_National_Park/carara-3.webp",
    "img/tours/jaco/Carara_National_Park/carara-4.webp",
    "img/tours/jaco/Carara_National_Park/carara-5.webp",
    "img/tours/jaco/Carara_National_Park/carara-6.webp",
    "img/tours/jaco/Carara_National_Park/carara-8.webp"
  ],
  "jaco/Chocolate_Tour": [
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-2.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-3.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-4.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-5.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-6.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-7.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px-8.webp",
    "img/tours/jaco/Chocolate_Tour/Chocolate-500px-x-500px.webp"
  ],
  "jaco/Extreme_Adrenaline_5_in_1": [
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-2.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-3.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-4.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-5.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-6.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-7.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-8.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-9.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-10.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1.webp"
  ],
  "jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit": [
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-2.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-5.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-6.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-7.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/carara-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-2.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-3.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-5.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico.webp"
  ],
  "jaco/Horseback_Riding_&_Waterfalls": [
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-2.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-3.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-4.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-5.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-6.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-7.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-8.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-9.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding.webp"
  ],
  "jaco/Monkey_Mangrove_Tour": [
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-2.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-3.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-4.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-5.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-6.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-7.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-8.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour-9-1.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Monkey-Tour.webp"
  ],
  "jaco/Poas_Volcano_&_La_Paz_Waterfall": [
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-2.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-3.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-4.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-5.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-6.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-7.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-8.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-9.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-10.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-11.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-12.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-13.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-14.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-15.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-16.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-17.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-18.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall.webp"
  ],
  "jaco/Safari_Adventure": [
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-2.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-3.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-4.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-5.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-6.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-7.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-8.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco.webp"
  ],
  "jaco/Sea_Kayak_&_Snorkel_Tour": [
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-2.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-3.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-4.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-5.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-6.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak.webp"
  ],
  "jaco/Tortuga_Island_Tour": [
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-2.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-3.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-4.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-5.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-6.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga-7.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Tortuga.webp"
  ],
  "jaco/Tranopy_Tour": [
    "img/tours/jaco/Tranopy_Tour/carara-2.webp",
    "img/tours/jaco/Tranopy_Tour/Teleferico.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-3.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-4.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-5.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-6.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-7.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-8.webp",
    "img/tours/jaco/Tranopy_Tour/Tranopy-9.webp"
  ],
  "jaco/Waterfall_Experience_Tour": [
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-2.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-3.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-4.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-5.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-6.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-7.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-8.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience.webp"
  ],
  "jaco/White _Water_Rafting": [
    "img/tours/jaco/White _Water_Rafting/Rafting-1.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-2.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-3.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-4.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-5.webp"
  ],
  "sj/Arenal_Volcano_and_Hot_Springs": [
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal_Volcano_and_Hot_Springs.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal-portada-trip-1024x683.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Volcan-Arenal-500-x-500-2.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Volcan-Arenal-500-x-500-3.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Volcan-Arenal-500-x-500-4.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Volcan-Arenal-500-x-500-5.webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Volcan-Arenal-500-x-500.webp"
  ],
  "sj/Beach_Day": [
    "img/tours/sj/Beach_Day/Beach-Day-2-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-3-1024x686.webp",
    "img/tours/sj/Beach_Day/Beach-Day-4.webp",
    "img/tours/sj/Beach_Day/Beach-Day-5.webp",
    "img/tours/sj/Beach_Day/Beach-Day-6-1024x682.webp",
    "img/tours/sj/Beach_Day/Beach-Day-7-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-8-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-9-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-10.webp",
    "img/tours/sj/Beach_Day/Beach-Day-11-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-12-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-13.webp",
    "img/tours/sj/Beach_Day/Beach-Day-1024x683.webp",
    "img/tours/sj/Beach_Day/Beach-Day-1024x768.webp"
  ],
  "sj/City_Bus": [
    "img/tours/sj/City_Bus/City-bus-2-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-3-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-4-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-5-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-6-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-8-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-9-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-10-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-11-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-12-1024x1024.webp",
    "img/tours/sj/City_Bus/City-bus-1024x768.webp",
    "img/tours/sj/City_Bus/City-bus-1024x1024.webp"
  ],
  "sj/Irazu_Volcano_Halfday": [
    "img/tours/sj/Irazu_Volcano_Halfday/1.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/2.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/Irazu-Medio-Dia-500px-x-500px-3.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/Irazu-Medio-Dia-500px-x-500px-4.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/Irazu-Medio-Dia-500px-x-500px-5.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/Irazu-Medio-Dia-500px-x-500px-6.webp"
  ],
  "sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden": [
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-2-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-3-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-4-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-5-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-6-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-7-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-8-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-9-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-10-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-11-1024x1024.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-1024x1024.webp"
  ],
  "sj/La_Paz_Waterfall_Gardens": [
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-2-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-3-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-4-1-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-5-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-6-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-7-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-8-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-9-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-10-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-11-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-12-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-13-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-14-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-15-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-16-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-17-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-18-1024x1024.webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La-Paz-Waterfall-Gardens-1024x1024.webp"
  ],
  "sj/Manuel_Antonio": [
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-2-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-3-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-4-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-5-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-6-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-7-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-8-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-9-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-10-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-11-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-12-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-13-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-14-1024x1024.webp",
    "img/tours/sj/Manuel_Antonio/Manuel-Antonio-1024x1024.webp"
  ],
  "sj/Natural_Combo": [
    "img/tours/sj/Natural_Combo/coffee-2-1024x1024.webp",
    "img/tours/sj/Natural_Combo/coffee-4-1024x1024.webp",
    "img/tours/sj/Natural_Combo/coffee-1024x1024.webp",
    "img/tours/sj/Natural_Combo/Irazu-Volcano-Orosi-Valley-Lankester-Botanic-Garden-9-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-2-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-3-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-4-1-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-6-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-7-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-8-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-9-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-10-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-11-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-12-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-13-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-14-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-15-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-17-1024x1024.webp",
    "img/tours/sj/Natural_Combo/La-Paz-Waterfall-Gardens-18-1024x1024.webp"
  ],
  "sj/Premium Tortuga Island_Tour": [
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-2-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-3-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-4-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-5-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-6-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-7-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-8-1024x1024.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/Premiun-Isla-Tortuga-1024x1024.webp"
  ],
  "sj/Typical_Dinner_and_Folklore_Show": [
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-2.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-3.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-4.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-5.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-6.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500-7.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/Folklore-500-x-500.webp"
  ]
};
