export const tourGalleryManifest = {
  "jaco/Aerial_Tram": [
    "img/tours/jaco/Aerial_Tram/Teleferico-2.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-3.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-4.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-5.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico-6.webp",
    "img/tours/jaco/Aerial_Tram/Teleferico.webp"
  ],
  "jaco/Canyoning_Tour": [
    "img/tours/jaco/Canyoning_Tour/Canyoning-2.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-3.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-4.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-5.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-6.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning-7.webp",
    "img/tours/jaco/Canyoning_Tour/Canyoning.webp"
  ],
  "jaco/Carara_National_Park": [
    "img/tours/jaco/Carara_National_Park/1.webp",
    "img/tours/jaco/Carara_National_Park/2.webp",
    "img/tours/jaco/Carara_National_Park/3.webp",
    "img/tours/jaco/Carara_National_Park/4.webp",
    "img/tours/jaco/Carara_National_Park/5.webp"
  ],
  "jaco/Chocolate_Tour": [
    "img/tours/jaco/Chocolate_Tour/1.webp",
    "img/tours/jaco/Chocolate_Tour/2.webp",
    "img/tours/jaco/Chocolate_Tour/3.webp",
    "img/tours/jaco/Chocolate_Tour/4.webp",
    "img/tours/jaco/Chocolate_Tour/5.webp",
    "img/tours/jaco/Chocolate_Tour/6.webp",
    "img/tours/jaco/Chocolate_Tour/7.webp",
    "img/tours/jaco/Chocolate_Tour/8.webp",
    "img/tours/jaco/Chocolate_Tour/9.webp",
    "img/tours/jaco/Chocolate_Tour/10.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-1.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-2.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-3.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-4.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-5.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-7.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-9.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-10.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-11.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-13.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-14.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-15.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-16.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-17.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-18.webp",
    "img/tours/jaco/Chocolate_Tour/Copia-de-19.webp"
  ],
  "jaco/Extreme_Adrenaline_5_in_1": [
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-2.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-3.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-4.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-5.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-6.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-7.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-8.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-9.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1-10.webp",
    "img/tours/jaco/Extreme_Adrenaline_5_in_1/5-in-1.webp"
  ],
  "jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit": [
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-2.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-5.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-6.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/5-in-1-7.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/carara-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-2.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-3.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-4.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico-5.webp",
    "img/tours/jaco/Half_day_pass_Aerial_Tram_and_High_Rope_Circuit/Teleferico.webp"
  ],
  "jaco/Horseback_Riding_&_Waterfalls": [
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-2.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-3.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-4.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-5.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-6.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-7.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-8.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding-9.webp",
    "img/tours/jaco/Horseback_Riding_&_Waterfalls/Horseback-Riding.webp"
  ],
  "jaco/Monkey_Mangrove_Tour": [
    "img/tours/jaco/Monkey_Mangrove_Tour/1.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/2.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/3.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/5.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/6.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/7.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/8.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/9.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/18.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/19.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/20.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/22.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/23.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/25.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/26.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-1.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-1(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-2(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-3.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-3(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-4.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-4(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-5.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-6.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-6(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-7.webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-7(1).webp",
    "img/tours/jaco/Monkey_Mangrove_Tour/Copia-de-10.webp"
  ],
  "jaco/Poas_Volcano_&_La_Paz_Waterfall": [
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-2.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-3.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-4.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-5.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-6.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-7.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-8.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-9.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-10.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-11.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-12.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-13.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-14.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-15.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-16.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-17.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall-18.webp",
    "img/tours/jaco/Poas_Volcano_&_La_Paz_Waterfall/Poas-Volcano-y-la-paz-waterfall.webp"
  ],
  "jaco/Safari_Adventure": [
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-2.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-3.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-4.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-5.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-6.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-7.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco-8.webp",
    "img/tours/jaco/Safari_Adventure/Safary-Jaco.webp"
  ],
  "jaco/Sea_Kayak_&_Snorkel_Tour": [
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-2.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-3.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-4.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-5.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak-6.webp",
    "img/tours/jaco/Sea_Kayak_&_Snorkel_Tour/Kayak.webp"
  ],
  "jaco/Tortuga_Island_Tour": [
    "img/tours/jaco/Tortuga_Island_Tour/1.webp",
    "img/tours/jaco/Tortuga_Island_Tour/2.webp",
    "img/tours/jaco/Tortuga_Island_Tour/3.webp",
    "img/tours/jaco/Tortuga_Island_Tour/4.webp",
    "img/tours/jaco/Tortuga_Island_Tour/5.webp",
    "img/tours/jaco/Tortuga_Island_Tour/6.webp",
    "img/tours/jaco/Tortuga_Island_Tour/7.webp",
    "img/tours/jaco/Tortuga_Island_Tour/8.webp",
    "img/tours/jaco/Tortuga_Island_Tour/9.webp",
    "img/tours/jaco/Tortuga_Island_Tour/10.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-1.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-1(1).webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-2.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-3.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-4.webp",
    "img/tours/jaco/Tortuga_Island_Tour/Copia-de-4(1).webp"
  ],
  "jaco/Tranopy_Tour": [
    "img/tours/jaco/Tranopy_Tour/1.webp",
    "img/tours/jaco/Tranopy_Tour/3.webp",
    "img/tours/jaco/Tranopy_Tour/6.webp",
    "img/tours/jaco/Tranopy_Tour/7.webp",
    "img/tours/jaco/Tranopy_Tour/8.webp",
    "img/tours/jaco/Tranopy_Tour/9.webp",
    "img/tours/jaco/Tranopy_Tour/10.webp",
    "img/tours/jaco/Tranopy_Tour/12.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-5.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-6.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-7.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-8.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-9.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-10.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-11.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-12.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-13.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-14.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-15.webp",
    "img/tours/jaco/Tranopy_Tour/Copia-de-16.webp"
  ],
  "jaco/Waterfall_Experience_Tour": [
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-2.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-3.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-4.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-5.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-6.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-7.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience-8.webp",
    "img/tours/jaco/Waterfall_Experience_Tour/Waterfall-Experience.webp"
  ],
  "jaco/White _Water_Rafting": [
    "img/tours/jaco/White _Water_Rafting/Rafting-1.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-2.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-3.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-4.webp",
    "img/tours/jaco/White _Water_Rafting/Rafting-5.webp"
  ],
  "sj/Arenal_Volcano_and_Hot_Springs": [
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (1).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (2).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (3).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (4).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (5).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (6).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (7).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (8).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal (9).webp",
    "img/tours/sj/Arenal_Volcano_and_Hot_Springs/Arenal.webp"
  ],
  "sj/Beach_Day": [
    "img/tours/sj/Beach_Day/1.webp",
    "img/tours/sj/Beach_Day/2.webp",
    "img/tours/sj/Beach_Day/3.webp",
    "img/tours/sj/Beach_Day/4.webp",
    "img/tours/sj/Beach_Day/5.webp",
    "img/tours/sj/Beach_Day/6.webp",
    "img/tours/sj/Beach_Day/7.webp",
    "img/tours/sj/Beach_Day/8.webp",
    "img/tours/sj/Beach_Day/9.webp",
    "img/tours/sj/Beach_Day/10.webp"
  ],
  "sj/City_Bus": [
    "img/tours/sj/City_Bus/1.webp",
    "img/tours/sj/City_Bus/2.webp",
    "img/tours/sj/City_Bus/3.webp",
    "img/tours/sj/City_Bus/4.webp",
    "img/tours/sj/City_Bus/5.webp",
    "img/tours/sj/City_Bus/6.webp",
    "img/tours/sj/City_Bus/7.webp",
    "img/tours/sj/City_Bus/8.webp",
    "img/tours/sj/City_Bus/9.webp",
    "img/tours/sj/City_Bus/10.webp"
  ],
  "sj/Irazu_Volcano_Halfday": [
    "img/tours/sj/Irazu_Volcano_Halfday/1.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/2.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/3.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/4.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/5.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/6.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/7.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/8.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/9.webp",
    "img/tours/sj/Irazu_Volcano_Halfday/10.webp"
  ],
  "sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden": [
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/1.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/2.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/3.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/4.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/5.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/6.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/7.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/8.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/9.webp",
    "img/tours/sj/Irazu_Volcano_Orisi_Valley_&_Lankester_Botanic_Garden/10.webp"
  ],
  "sj/La_Paz_Waterfall_Gardens": [
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (1).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (2).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (3).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (4).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (5).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (6).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (7).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (8).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall (9).webp",
    "img/tours/sj/La_Paz_Waterfall_Gardens/La Paz Waterfall.webp"
  ],
  "sj/Manuel_Antonio": [
    "img/tours/sj/Manuel_Antonio/1.webp",
    "img/tours/sj/Manuel_Antonio/2.webp",
    "img/tours/sj/Manuel_Antonio/3.webp",
    "img/tours/sj/Manuel_Antonio/4.webp",
    "img/tours/sj/Manuel_Antonio/5.webp",
    "img/tours/sj/Manuel_Antonio/6.webp",
    "img/tours/sj/Manuel_Antonio/7.webp",
    "img/tours/sj/Manuel_Antonio/8.webp",
    "img/tours/sj/Manuel_Antonio/9.webp",
    "img/tours/sj/Manuel_Antonio/10.webp"
  ],
  "sj/Natural_Combo": [
    "img/tours/sj/Natural_Combo/Combo (1).webp",
    "img/tours/sj/Natural_Combo/Combo (2).webp",
    "img/tours/sj/Natural_Combo/Combo (3).webp",
    "img/tours/sj/Natural_Combo/Combo (4).webp",
    "img/tours/sj/Natural_Combo/Combo (5).webp",
    "img/tours/sj/Natural_Combo/Combo (6).webp",
    "img/tours/sj/Natural_Combo/Combo (7).webp",
    "img/tours/sj/Natural_Combo/Combo (8).webp",
    "img/tours/sj/Natural_Combo/Combo (9).webp",
    "img/tours/sj/Natural_Combo/Combo.webp"
  ],
  "sj/Premium Tortuga Island_Tour": [
    "img/tours/sj/Premium Tortuga Island_Tour/1.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/2.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/3.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/4.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/5.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/6.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/7.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/8.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/9.webp",
    "img/tours/sj/Premium Tortuga Island_Tour/10.webp"
  ],
  "sj/Typical_Dinner_and_Folklore_Show": [
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/1.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/2.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/3.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/4.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/5.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/6.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/7.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/8.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/9.webp",
    "img/tours/sj/Typical_Dinner_and_Folklore_Show/10.webp"
  ]
};
